import "./globals.css";
import { UserProvider } from "../UserContext";

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, map }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/gaf4wjv.css"></link>


      </head>
            <body>
        <UserProvider initialUser={null}>
        <div style={{ height: '100vh', width: '100vw' }}>
          {map}
        </div>
        <div style={{}}>
          {children}
        </div>
        </UserProvider>
      </body>
    </html>
  );
}
