import { Geist, Geist_Mono } from "next/font/google";
import "./globals.css";

const geistSans = Geist({
  variable: "--font-geist-sans",
  subsets: ["latin"],
});

const geistMono = Geist_Mono({
  variable: "--font-geist-mono",
  subsets: ["latin"],
});

export const metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({ children, map }) {
  return (
    <html lang="en">
      <head>
        <link rel="stylesheet" href="https://use.typekit.net/gaf4wjv.css"></link>


      </head>
            <body className={`${geistSans.variable} ${geistMono.variable}`}>
        
        <div>
          {children}
        </div>
        <div style={{ height: '100vh', width: '100vw' }}>
          {map}
        </div>
      </body>
    </html>
  );
}
